### PR TITLE
Add new plugin android_id to list

### PR DESCRIPTION
**Pull request by nohli**

### CODE REVIEW

**Review by vbuberen — APPROVED** [review]

**Comment by nohli** [comment]
@jeroen-meijer do you have write-access to this repo?

**Comment by jeroen-meijer** [comment]
> @jeroen-meijer do you have write-access to this repo?

Hi there! 👋🏻 

I do, though I don't do community related tasks that often these days.
I'll go ahead and merge this. In the meantime, I'll ping @mhadaily to make him aware of this, as he runs most community operations last time I checked.

Thanks!

**Comment by mhadaily** [comment]
I thought we are going to have this plugin under PLUS plugins, isn't that the case?

I will do that as soon as I have time, Let's talk about this in our Plus plugin channel on FSG.

**Comment by vbuberen** [comment]
> I thought we are going to have this plugin under PLUS plugins, isn't that the case?
> 

I don't like this idea. I would even split Plus plugins into their own repos. 
Reasons - to not have a big pile of issues for different plugins onside one repo and nice release management with tags, so one repo has one plugin only with tags for itself.
But yeah, let's discuss in Slack as you suggested.

**Pull request merged**
